### ISSUE TITLE
 issue with jupyter notebook

### ISSUE THREAD

**Issue by subpath** [tinctura13/fishing_sinker#1]
Hey! Super excited about your code, I would like to use it for my Batya as well, but Jupyter notebook you included in the repo is not parsing by GitHub and nb viewer, could you please take a look?

**Comment by tinctura13** [comment]
Sup! Sure, I will check it asap.

**Comment by tinctura13** [comment]
Hi! I've just fixed it up, you can check it!

**Comment by subpath** [comment]
Awesome! Thanks!
